### PR TITLE
Fixed Social Login (Facebook, Twitter and Linkedin).

### LINKED ISSUE #61: Un usuario reporta que no pudo entrar con FB
<a href="https://github.com/rodowi"></img></a> **Issue by [rodowi](https://github.com/rodowi)**
_Fri May  8 23:34:04 2015_
_Originally opened as https://github.com/mxabierto/madison/issues/227_

----

"entre en la página para registro y no pude registrarme con FB":
http://www.gob.mx/participa/user/login

### PR DESCRIPTION
**Pull request by codemoe**
Removed use of scopes when logging with Twitter. Added growlMessage method to abstract controller (this method is used on several places). Minor fixes and improvements to updateEmail method and ProfileCompletionMessage js. Added User model route binding. Probably resolves #61

### CODE REVIEW

File: app/Http/Controllers/AbstractController.php [hunk 1]
```diff
@@ -9,4 +9,41 @@
...
+                //Set that severity for every message
+                foreach ($messages as $message) {
+                    array_push($growled['messages'], ['text' => $message, 'severity' => $severity]);
+                }
+            } elseif (count($message) === count($severity)) { //Ensure we have the same number of messages <=> severities
+                foreach ($messages as $index => $message) {
+                    array_push($growled['messages'], ['text' => $message, 'severity' => $severity[$index]]);
+                }
+            } else { //Throw an exception if there's a mismatch
+                throw new Exception("Unable to create growl message array because of size mismatches");
```
Comment (joecohens) [inline app/Http/Controllers/AbstractController.php]: @codemoe Necesitas importart Exception
